language: php
php:
  - "5.4"
  - "5.3"

before_script:
    - sudo apt-get install apache2
    - sudo a2enmod actions
    - sudo a2enmod rewrite
    - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
    - echo "$(curl -fsSL https://raw.github.com/gist/3728514/e9297a5c1ff408be03713a8bc4faf1d93d82af39/travis-ci-phpenv-sugarcrmce.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
    - echo "$(curl -fsSL https://raw.github.com/gist/3728514/8066fda124b6c86f69ad32a010b8c22bbaf868e8/travis-ci-vhost-sugarcrmce.txt)" | sed -e "s,PATH,`pwd`,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
    - sudo service apache2 restart
    - mysql -u root -e "CREATE USER 'sugarcrm'@'localhost' IDENTIFIED BY 'sugarcrm'"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'sugarcrm'@'localhost' WITH GRANT OPTION;"
