language: php
php:
  - "5.4"
  - "5.3"

before_script:
    - cp .travis/config_si.php `pwd`
    - sudo apt-get install apache2
    - sudo a2enmod actions
    - sudo a2enmod rewrite
    - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
    - cat .travis/travis-ci-phpenv-sugarcrmce.txt | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
    - cat .travis/travis-ci-vhost-sugarcrmce.txt | sed -e "s,PATH,`pwd`,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
    - sudo service apache2 restart
    - mysql -u root -e "CREATE USER 'sugarcrm'@'localhost' IDENTIFIED BY 'sugarcrm'"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'sugarcrm'@'localhost' WITH GRANT OPTION;"
    - curl 'http://localhost/install.php'
    - cd tests

script: phpunit --verbose --coverage-text
